API_KEY="efc307e5d8msh4de8db72ff57f64p1e9573jsn86b08a91a938"
CHANGABLE_KEY_ITEMS = {
    "lat": ["latitude", "lat"],
    "lon": ["longitude", "lon"],
    "tz_id": ["timezone", "tz"],
    "localtime": "localtime",
    "last_updated": "last updated",
    "temp_c": ["temperature in celsius",'C'],
    "temp_f": ["temperature in fahrenheit",'F'],
    "is_day": "is day",
    "wind_mph": ["wind in meters per hour", "mph"],
    "wind_kph": ["wind in kilometers per hour", "kph"],
    "wind_degree": "wind degree",
    "wind_dir": "wind direction",
    "pressure_mb": ["pressure in millibars", "mb"],
    "pressure_in": ["pressure in inches", "in"],
    "precip_mm": ["precipitation in millimeter", "mm"],
    "precip_in": ["precipitation in inches", "in"],
    "humidity": "humidity",
    "cloud": "cloud",
    "feelslike_c": ["feels like in celsius", 'C'],
    "feelslike_f": ["feels like in fahrenheit", 'F'],
    "vis_km": ["visibility in km", "km"],
    "vis_miles": ["visibility in miles", "miles"],
    "uv": "uv",
    "gust_mph": ["gust in meters per hour", "mph"],
    "gust_kph": ["gust in kilometers per hour", "kph"],
}